name: insights

on: push

jobs:
  phpinsights:
    name: PHP Insights
    uses: XNXKTech/workflows/.github/workflows/laravel-insights.yml@main
    with:
      versions: "[\"8.0\", \"8.1\"]"
      stability: "[\"prefer-lowest\", \"prefer-stable\"]"